### PR TITLE
add check for cargo

### PR DESCRIPTION
**Pull request by bmacer**

### CODE REVIEW

**Comment by bmacer** [comment]
proposed fix for #56

**Review by x5a — APPROVED** [review]

**Comment by x5a** [comment]
Hey @bmacer, thanks for submitting. We require signed commits to merge your changes:
* [Github signed commits documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)
* [SO post on signing past commits](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits)

**Comment by bmacer** [comment]
thanks @x5a i think i fumbled my way through signing post-commit.  thanks for the links.  hope all is good now.

will sign going forward!

**Comment by x5a** [comment]
thanks for contributing @bmacer

**Pull request merged**
